# _config.yml
markdown: kramdown
theme: jekyll-theme-slate  # You can keep this or remove it since you're not using a theme

# Link to your custom CSS
include:
  - styles.css

title: Benedick's Spatial Data Science Portfolio
description: Benedick's past and present works as an aspiring data scientist
Color: Dark Blue
Font: Times New Roman, 18
Position: Center



